config/routes.rb
Rails.application.routes.draw do
  # Routes for User authentication
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :notes_permissions, only: [ :index, :destroy, :update_permission ]
  # Nested routes for notes
  resources :notes, except: [ :index ] do
    member do
      post "share"  # Route for sharing a note
    end
  end

  # Route for viewing all shared notes
  get "shared_notes", to: "notes_permissions#index", as: "shared_notes" # Use appropriate controller

  # Root route
  root "home#index"  # Redirect to the home page
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        if user_signed_in?
            @notes = current_user.notes.all
        end
    end
end

app/views/home/_landing.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-4">
    <div class="grid grid-cols-1 md:grid-cols-2">
        <div class="flex flex-col place-content-center items-center md:items-start py-16">
            <h1 class="text-6xl font-light leading-7 text-black">Journal</h1>
            <h2 class="mt-6 text-2xl font-light leading-2 text-black">Effortlessly organize your journal</h2>

            <%= link_to 'Get Started', new_user_registration_path, class:'mt-8 text-xl border border-black rounded-md py-2 px-6 hover:-ml-1 hover:mt-7 hover: border-b-4 hover: border-r-4' %>
            
        </div>
        <%= image_tag 'journal_graphics.svg', class: 'mx-auto w-72 md:w-full py-0 md:py-16 ' %>
    </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? && @notes.count > 0 %>
  <div class="mx-auto my-5 max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
    <!-- Flex Container for Notes -->
    <div id="notes" class="flex flex-wrap -mx-4">
      <!-- Add Note Button -->
      <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-4 mb-8">
        <%= link_to new_note_path, class:"flex flex-col gap-2 text-xl items-center place-content-center border border-black rounded-md p-4 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4 transition-all h-full" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
          <span class="mt-2 text-lg">Add Note</span>
        <% end %>
      </div>

      <!-- Notes -->
      <% @notes.each do |note| %>
        <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-4 mb-8">
          <%= link_to note_path(note.id), class:"border border-black rounded-md p-4 hover:-ml-1 hover:-mt-1 hover:border-b-4 hover:border-r-4 transition-transform h-full flex flex-col" do %>
            <p class="text-2xl font-bold mb-2"><%= note.title.truncate(24) %></p>
            
            <!-- Date -->
            <p class="text-sm text-gray-600 font-medium mb-4"><%= note.created_at.strftime("%d %b") %></p>

            <!-- Description -->
            <p class="mt-3 text-gray-800 flex-grow"><%= note.description.truncate(100) %></p>

            <!-- File Type Icons -->
            <div class="mt-4 flex items-center space-x-2">
              <% image_count = note.files.select { |file| file.image? }.count %>
              <% video_count = note.files.select { |file| file.video? }.count %>
              <% pdf_count = note.files.select { |file| file.content_type == 'application/pdf' }.count %>

              <!-- Image Icon -->
              <% if image_count > 0 %>
                <%= image_tag 'image.png', size: '20x20', alt: 'Image', class: 'inline-block' %>
                <span class="text-xs font-semibold"><%= image_count %></span>
              <% end %>

              <!-- Video Icon -->
              <% if video_count > 0 %>
                <%= image_tag 'video.png', size: '20x20', alt: 'Video', class: 'inline-block' %>
                <span class="text-xs font-semibold"><%= video_count %></span>
              <% end %>

              <!-- PDF Icon -->
              <% if pdf_count > 0 %>
                <%= image_tag 'pdf_icon.png', size: '20x20', alt: 'PDF', class: 'inline-block' %>
                <span class="text-xs font-semibold"><%= pdf_count %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
<% else %>
  <%= render 'home/landing' %>
<% end %>