config/routes.rb
Rails.application.routes.draw do
  # Routes for User authentication
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :notes_permissions, only: [ :index, :destroy, :update_permission ]
  # Nested routes for notes
  resources :notes, except: [ :index ] do
    member do
      post "share"  # Route for sharing a note
    end
  end

  # Route for viewing all shared notes
  get "shared_notes", to: "notes_permissions#index", as: "shared_notes" # Use appropriate controller

  # Root route
  root "home#index"  # Redirect to the home page
end

app/views/layouts/_header.html.erb
<nav class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="flex h-20 justify-between">
            <div class="flex">
                <%= link_to 'Journal', root_path,class: 'flex flex-shrink-0 font-medium text-3xl items-center' %>
            </div>
            <div class="ml-6 flex items-center gap-4">
                <% if user_signed_in? %>
                    <%= link_to 'Shared Notes', shared_notes_path, class: 'border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover: border-b-4 hover: border-r-4' %>
                    <%= link_to 'Add Note', new_note_path, class:"border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover: border-b-4 hover: border-r-4"%>
                    <%= link_to 'Log out', destroy_user_session_path, data: {"turbo-method": :delete}, class:"border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover: border-b-4 hover: border-r-4"%>
                <% else %>
                    <%= link_to 'Log in', new_user_session_path, class:"border border-black rounded-md py-2 px-6 hover:-ml-1 hover:-mt-1 hover: border-b-4 hover: border-r-4"%>
                <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="flex place-content-center font-regular leading-8 bg-green-500"><%= notice %></p>  
    <p class="flex place-content-center font-regular leading-8 bg-red-500"><%= alert %></p> 
    <% unless controller_name == 'registrations'|| controller_name == 'sessions' || controller_name == 'passwords' %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= yield %>

  </body>
</html>